services:
  # ADMIN LARAVEL (MODULE C) - admin.ub2023.hu
  admin-laravel:
    image: ws2024s17hur3-admin-laravel
    build:
      dockerfile: ./Dockerfile.php
      context: .
    restart: always
    ports:
      - "2223:22"
    volumes:
      - ../www/admin-laravel:/app
    environment:
      WEB_DOCUMENT_ROOT: /app/public
    labels:
      traefik.enable: "true"
      traefik.http.routers.admin.rule: HostRegexp(`{_:admin\..*}`)
      traefik.http.services.admin.loadbalancer.server.port: 80