services:
  # BACKEND NODEJS (MODULE C) - backend.ub2023.hu
  backend-nodejs:
    image: ws2024s17hur3-backend-nodejs
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    working_dir: /app
    volumes:
      - ../www/backend-nodejs:/app
    labels:
      traefik.enable: "true"
      traefik.http.routers.backend.rule: HostRegexp(`{_:backend\..*}`)
      traefik.http.services.backend.loadbalancer.server.port: 80